<a href="https://colab.research.google.com/github/Gustavoo-z/imersao-python-pd/blob/main/imersao_dados_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# An√°lise de Dados com Pandas

In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/main/salaries.csv")

In [13]:
df.head(10)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M
5,2025.0,EN,FT,Data Engineer,80000,USD,80000,US,0,US,M
6,2025.0,SE,FT,Data Scientist,185000,USD,185000,US,0,US,M
7,2025.0,SE,FT,Data Scientist,148000,USD,148000,US,0,US,M
8,2025.0,MI,FT,Data Scientist,135000,USD,135000,CA,0,CA,M
9,2025.0,MI,FT,Data Scientist,108000,USD,108000,CA,0,CA,M

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [15]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [16]:
df.shape

(133349, 11)

In [17]:
linhas, colunas = df.shape[0], df.shape[1]
print("Linhas:", linhas)
print("Colunas:", colunas)

Linhas: 133349
Colunas: 11

In [18]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [19]:
# Dicion√°rio para traduzir os nomes das colunas
traducao_colunas = {
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
}

# Renomear as colunas do DataFrame
df = df.rename(columns=traducao_colunas)

display(df.columns)

Index(['ano', 'senioridade', 'contrato', 'cargo', 'salario', 'moeda', 'usd',
       'residencia', 'remoto', 'empresa', 'tamanho_empresa'],
      dtype='object')

In [20]:
df["senioridade"].value_counts()

senioridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [21]:
df["contrato"].value_counts()

contrato
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [22]:
df["remoto"].value_counts()

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [23]:
df["tamanho_empresa"].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [24]:
df["senioridade"].value_counts()

senioridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [25]:
traducao_remoto = {
    0: 'Presencial',
    50: 'H√≠brido',
    100: 'Remoto'
}

df['remoto'] = df['remoto'].replace(traducao_remoto)

display(df['remoto'].value_counts())

remoto
Presencial    105312
Remoto         27718
H√≠brido          319
Name: count, dtype: int64

In [26]:
traducao_contrato = {
    'FT': 'Tempo Integral',
    'CT': 'Contrato',
    'PT': 'Meio Per√≠odo',
    'FL': 'Freelancer'
}

df['contrato'] = df['contrato'].replace(traducao_contrato)

display(df['contrato'].value_counts())

contrato
Tempo Integral    132563
Contrato             394
Meio Per√≠odo         376
Freelancer            16
Name: count, dtype: int64

In [27]:
traducao_tamanho_empresa = {
    'M': 'M√©dio',
    'L': 'Grande',
    'S': 'Pequeno'
}

df['tamanho_empresa'] = df['tamanho_empresa'].replace(traducao_tamanho_empresa)

display(df['tamanho_empresa'].value_counts())

tamanho_empresa
M√©dio      129561
Grande       3574
Pequeno       214
Name: count, dtype: int64

In [28]:
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,SE,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M√©dio
1,2025.0,SE,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M√©dio
2,2025.0,MI,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M√©dio
3,2025.0,MI,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M√©dio
4,2025.0,EN,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M√©dio

In [29]:
df.describe(include='object')

,senioridade,contrato,cargo,moeda,residencia,remoto,empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,SE,Tempo Integral,Data Scientist,USD,US,Presencial,US,M√©dio
freq,77241,132563,17314,126140,119579,105312,119641,129561

# Prepara√ß√£o e limpeza dos Dados

In [30]:
df.isnull()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
133344,False,False,False,False,False,False,False,False,False,False,False
133345,False,False,False,False,False,False,False,False,False,False,False
133346,False,False,False,False,False,False,False,False,False,False,False
133347,False,False,False,False,False,False,False,False,False,False,False
133348,False,False,False,False,False,False,False,False,False,False,False

In [31]:
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,SE,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M√©dio
1,2025.0,SE,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M√©dio
2,2025.0,MI,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M√©dio
3,2025.0,MI,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M√©dio
4,2025.0,EN,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M√©dio

In [32]:
df.isnull().sum()

ano                10
senioridade         0
contrato            0
cargo               0
salario             0
moeda               0
usd                 0
residencia          0
remoto              0
empresa             0
tamanho_empresa     0
dtype: int64

In [33]:
df['ano'].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [34]:
df[df.isnull().any(axis=1)]

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
5588,NaN,SE,Tempo Integral,Product Manager,184500,USD,184500,US,Presencial,US,M√©dio
59692,NaN,MI,Tempo Integral,Engineer,110000,USD,110000,DE,Presencial,DE,M√©dio
59710,NaN,EN,Tempo Integral,Data Scientist,208800,USD,208800,US,Presencial,US,M√©dio
59759,NaN,SE,Tempo Integral,Software Engineer,135000,USD,135000,US,Presencial,US,M√©dio
59789,NaN,SE,Tempo Integral,Engineer,112000,USD,112000,US,Presencial,US,M√©dio
131000,NaN,SE,Tempo Integral,Machine Learning Engineer,163800,USD,163800,US,Presencial,US,M√©dio
131006,NaN,SE,Tempo Integral,Data Analytics Manager,204500,USD,204500,US,Presencial,US,M√©dio
133054,NaN,EN,Tempo Integral,Data Scientist,40000,USD,40000,JP,Remoto,MY,Grande
133281,NaN,MI,Tempo Integral,Machine Learning Engineer,180000,PLN,46597,PL,Remoto,PL,Grande
133317,NaN,MI,Tempo Integral,Data Scientist,130000,USD,130000,US,H√≠brido,US,Grande

In [43]:
import numpy as np

# Cria√ß√£o de um dataframe para teste
df_salarios = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniele', "Val"],
    'salario': [4000, np.nan, 5000, np.nan, 100000]
})

# Calcula m√©dia, substitui os nulos e arredonda valores
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))

# Calcula mediana e substitui os nulos pela mediana
df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())

df_salarios

      nome   salario  salario_media  salario_mediana
0      Ana    4000.0        4000.00           4000.0
1    Bruno       NaN       36333.33           5000.0
2   Carlos    5000.0        5000.00           5000.0
3  Daniele       NaN       36333.33           5000.0
4      Val  100000.0      100000.00         100000.0

In [42]:
df_temperaturas = pd.DataFrame({
    'dia': ['Segunda', 'Ter√ßa', 'Quarta', 'Quinta', 'Sexta'],
    'temperatura': [30, np.nan, np.nan, 28, 27]
})

# Preenche os valores ausentes (NaN) para frente (forward fill)
df_temperaturas['preenchido_ffill'] = df_temperaturas['temperatura'].ffill()

# Preenche os valores ausentes (NaN) para tr√°s (backward fill)
df_temperaturas['preenchido_bfill'] = df_temperaturas['temperatura'].bfill()

df_temperaturas

       dia  temperatura  preenchido_ffill  preenchido_bfill
0  Segunda         30.0              30.0              30.0
1    Ter√ßa          NaN              30.0              28.0
2   Quarta          NaN              30.0              28.0
3   Quinta         28.0              28.0              28.0
4    Sexta         27.0              27.0              27.0

In [47]:
df_cidades = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniele', "Val"],
    'cidade': ['S√£o Paulo', np.nan, 'Curitiba', np.nan, 'Bel√©m']
})

# Preenche os valores ausentes na coluna 'cidade' com o texto 'N√£o informado'
df_cidades['cidade_preenchida'] = df_cidades['cidade'].fillna('N√£o informado')

df_cidades

      nome     cidade cidade_preenchida
0      Ana  S√£o Paulo         S√£o Paulo
1    Bruno        NaN     N√£o informado
2   Carlos   Curitiba          Curitiba
3  Daniele        NaN     N√£o informado
4      Val      Bel√©m             Bel√©m

In [50]:
df_limpo = df.dropna()
df_limpo.isnull().sum()

ano                0
senioridade        0
contrato           0
cargo              0
salario            0
moeda              0
usd                0
residencia         0
remoto             0
empresa            0
tamanho_empresa    0
dtype: int64

In [56]:
df_limpo.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025,SE,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M√©dio
1,2025,SE,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M√©dio
2,2025,MI,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M√©dio
3,2025,MI,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M√©dio
4,2025,EN,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M√©dio

In [55]:
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ano              133339 non-null  int64
 1   senioridade      133339 non-null  object
 2   contrato         133339 non-null  object
 3   cargo            133339 non-null  object
 4   salario          133339 non-null  int64
 5   moeda            133339 non-null  object
 6   usd              133339 non-null  int64
 7   residencia       133339 non-null  object
 8   remoto           133339 non-null  object
 9   empresa          133339 non-null  object
 10  tamanho_empresa  133339 non-null  object
dtypes: int64(3), object(8)
memory usage: 12.2+ MB

In [57]:
df_limpo = df_limpo.assign(ano = df_limpo['ano'].astype('int64'))
df_limpo

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025,SE,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M√©dio
1,2025,SE,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M√©dio
2,2025,MI,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M√©dio
3,2025,MI,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M√©dio
4,2025,EN,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M√©dio
...,...,...,...,...,...,...,...,...,...,...,...
133344,2020,SE,Tempo Integral,Data Scientist,412000,USD,412000,US,Remoto,US,Grande
133345,2021,MI,Tempo Integral,Principal Data Scientist,151000,USD,151000,US,Remoto,US,Grande
133346,2020,EN,Tempo Integral,Data Scientist,105000,USD,105000,US,Remoto,US,Pequeno
133347,2020,EN,Contrato,Business Data Analyst,100000,USD,100000,US,Remoto,US,Grande
133348,2021,SE,Tempo Integral,Data Scientist,7000000,INR,94665,IN,H√≠brido,IN,Grande